"""empty message

Revision ID: 4c5c0e5922a5
Revises: ffd3ab6cd82c
Create Date: 2018-12-24 12:55:59.050397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c5c0e5922a5'
down_revision = 'ffd3ab6cd82c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_info', sa.Column('map', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_info', 'map')
    # ### end Alembic commands ###
