"""clan name added to user model

Revision ID: ffd3ab6cd82c
Revises: 51c5ad266325
Create Date: 2018-10-29 12:48:42.848538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd3ab6cd82c'
down_revision = '51c5ad266325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('clan_name', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'clan_name')
    # ### end Alembic commands ###
